#!/usr/bin/env sh
# Entrypoint for the conformance provider container.
#
# Bootstraps the database, seeds the deterministic test client/user,
# and starts Django over HTTPS via ``gunicorn``. The conformance suite
# enforces ``https://`` for OIDC discovery — see
# ``CheckDiscEndpointAllEndpointsAreHttps`` — and Django's stock
# ``runserver`` does not speak TLS, so we use gunicorn with a
# self-signed cert generated by ``tests/conformance/tls/gen.sh``.
# ``--workers 1`` keeps the test setup deterministic and matches
# ``runserver`` semantics; ``--reload`` is intentionally omitted to
# avoid the auto-reloader's double-import side effects on AA startup.
set -eu

export DJANGO_SETTINGS_MODULE=tests.conformance.conformance_settings
export PYTHONUNBUFFERED=1

# Migrate first so seed has tables to write into. ``--run-syncdb``
# covers AA models that lack initial migrations on a fresh DB.
uv run python -m django migrate --run-syncdb --noinput

# Seed the conformance client and user. Idempotent.
uv run python tests/conformance/seed.py

# Bind to all interfaces so the suite container can reach us by
# Docker DNS (``provider:8443``). Cert + key were copied into the
# image build context from ``tests/conformance/tls/``.
exec uv run gunicorn \
    --bind 0.0.0.0:8443 \
    --workers 1 \
    --certfile /app/tests/conformance/tls/provider.crt \
    --keyfile /app/tests/conformance/tls/provider.key \
    --access-logfile - \
    tests.conformance.wsgi:application
