# Generated by Django 4.2.27 on 2026-05-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allianceauth_oidc', '0008_alter_allianceauthapplication_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allianceauthapplication',
            options={'ordering': ('name',), 'permissions': [('access_oidc', 'Can Authenticate External Apps with OIDC')], 'verbose_name': 'Alliance Auth OIDC application', 'verbose_name_plural': 'Alliance Auth OIDC applications'},
        ),
    ]
