# Generated by Django 5.2.14 on 2026-05-14 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "allianceauth_oidc",
            "0016_alter_allianceauthapplication_active_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuedCodeAudit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        help_text="sha256 hex digest of the authorization code. One-way by construction — the plaintext code is never stored.",
                        max_length=64,
                        verbose_name="Code hash",
                    ),
                ),
                (
                    "access_token_pk",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Integer primary key of the AccessToken row issued by this code exchange. Resolved at reuse-detection time.",
                        null=True,
                        verbose_name="Access token PK",
                    ),
                ),
                (
                    "refresh_token_pk",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Integer primary key of the RefreshToken row issued by this code exchange. Resolved at reuse-detection time.",
                        null=True,
                        verbose_name="Refresh token PK",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "reuse_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this code was presented at /o/token/ after the original exchange. >= 1 indicates a security-relevant replay attempt.",
                        verbose_name="Reuse count",
                    ),
                ),
                (
                    "last_reuse_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last reuse at"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Issued authorization code audit",
                "verbose_name_plural": "Issued authorization code audits",
                "indexes": [
                    models.Index(
                        fields=["reuse_count", "created_at"],
                        name="aaoidc_audit_cleanup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code_hash", "application"),
                        name="uniq_codehash_per_app",
                    )
                ],
            },
        ),
    ]
