# Generated by Django 5.2.16 on 2026-07-27 06:37
# Hand-edited: opens with a conditional row-format pre-step (see
# ``_ensure_dynamic_row_format``) so the client_id AlterField below can
# build its 1020-byte unique index on legacy-format InnoDB tables.

import oauth2_provider.generators
from django.db import migrations, models

# Row formats whose index-key limit is 767 bytes. The client_id
# AlterField below rebuilds a unique index over 255 utf8mb4 chars
# (1020 bytes), which fails with ``ERROR 1071`` on these; ``DYNAMIC``
# (the default since MariaDB 10.2 / MySQL 5.7) allows 3072 bytes.
_LEGACY_ROW_FORMATS = ("compact", "redundant")


def _ensure_dynamic_row_format(apps, schema_editor):
    """
    Convert the application table to ``ROW_FORMAT=DYNAMIC`` when needed.

    Only acts on a MySQL-family backend whose ``information_schema``
    reports a legacy ``COMPACT``/``REDUNDANT`` format for this app's
    table — anywhere else (sqlite, PostgreSQL, already-DYNAMIC tables)
    it issues no DDL. The table is operator-populated and tiny
    (dozens of rows at most), so the rebuild is instantaneous.
    """
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return
    table = apps.get_model(
        "allianceauth_oidc", "AllianceAuthApplication"
    )._meta.db_table
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT ROW_FORMAT FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s",
            [table],
        )
        row = cursor.fetchone()
        if row is None or str(row[0]).lower() not in _LEGACY_ROW_FORMATS:
            return
        quote = connection.ops.quote_name
        # Identifier comes from model meta and is quoted via the
        # backend's own quoter; no user input reaches the statement.
        cursor.execute(
            f"ALTER TABLE {quote(table)} ROW_FORMAT=DYNAMIC"  # nosec B608
        )


class Migration(migrations.Migration):
    dependencies = [
        ("allianceauth_oidc", "0020_alter_backchannellogoutattempt_jti"),
    ]

    operations = [
        # Must run BEFORE the client_id AlterField: that operation
        # rebuilds the unique index whose 1020-byte key overflows the
        # 767-byte limit of legacy row formats. Reverse is a no-op —
        # DYNAMIC is a safe format to leave behind on rollback.
        migrations.RunPython(
            _ensure_dynamic_row_format,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="allianceauthapplication",
            name="cimd_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the cached Client ID Metadata Document should be re-fetched",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allianceauthapplication",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("dcr", "Dynamic Client Registration"),
                    ("cimd", "Client ID Metadata Document"),
                ],
                default="manual",
                help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=255,
                unique=True,
            ),
        ),
    ]
