# Generated by Django 5.2.17 on 2026-09-19 09:12

import django.db.models.deletion
import oauth2_provider.generators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "allianceauth_oidc",
            "0021_allianceauthapplication_cimd_expires_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="algorithm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No OIDC support"),
                    ("RS256", "RSA with SHA-2 256"),
                    ("HS256", "HMAC with SHA-2 256"),
                ],
                default="",
                max_length=5,
                verbose_name="algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
                verbose_name="allowed origins",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    (
                        "urn:ietf:params:oauth:grant-type:device_code",
                        "Device Code",
                    ),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
                verbose_name="authorization grant type",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="cimd_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the cached Client ID Metadata Document should be re-fetched",
                null=True,
                verbose_name="CIMD expires at",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=255,
                unique=True,
                verbose_name="client ID",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("confidential", "Confidential"),
                    ("public", "Public"),
                ],
                max_length=32,
                verbose_name="client type",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created"
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="hash_client_secret",
            field=models.BooleanField(
                default=True, verbose_name="hash client secret"
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
                verbose_name="post logout redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="redirect_uris",
            field=models.TextField(
                blank=True,
                help_text="Allowed URIs list, space separated",
                verbose_name="redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("dcr", "Dynamic Client Registration"),
                    ("cimd", "Client ID Metadata Document"),
                ],
                default="manual",
                help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                max_length=32,
                verbose_name="registration source",
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="skip_authorization",
            field=models.BooleanField(
                default=False, verbose_name="skip authorization"
            ),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="allianceauthapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
